# Generated by Django 3.0.6 on 2020-05-27 16:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_group_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='g_name',
            new_name='group_name',
        ),
        migrations.AddField(
            model_name='core',
            name='category',
            field=models.CharField(default='FoodGroup', max_length=10),
        ),
        migrations.AddField(
            model_name='core',
            name='cookTime',
            field=models.CharField(default='15Min', max_length=20),
        ),
        migrations.AddField(
            model_name='core',
            name='ingredients',
            field=models.CharField(default='Ingredients', max_length=200),
        ),
        migrations.AddField(
            model_name='core',
            name='prepTime',
            field=models.CharField(default='5Min', max_length=20),
        ),
        migrations.AddField(
            model_name='core',
            name='process',
            field=models.CharField(default='Process', max_length=200),
        ),
        migrations.AlterField(
            model_name='group',
            name='published',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='group',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Core'),
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
