# Generated by Django 3.0.6 on 2020-05-27 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200527_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='core',
            name='author',
        ),
        migrations.AlterField(
            model_name='core',
            name='ingredients',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='core',
            name='process',
            field=models.TextField(null=True),
        ),
    ]
