# Generated by Django 3.0.6 on 2020-05-28 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200528_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='core',
            name='thumb',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
