# Generated by Django 3.0.6 on 2020-05-29 12:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200529_0957'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_name', models.CharField(max_length=200)),
                ('published', models.DateField(default=django.utils.timezone.now)),
                ('recipe', models.ManyToManyField(to='core.Core')),
            ],
        ),
    ]
